USE ForensicsThesis;
GO

CREATE TABLE OS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	OS_NAME VARCHAR(50),
	ARCHITECTURE VARCHAR(10),
	KERNEL VARCHAR(50),
	MEMORY INT
);

CREATE TABLE ACT(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ACT_NAME VARCHAR(100)
);

CREATE TABLE OS_ACT(
	ID_OS INT,
	ID_ACT INT
);

GO

ALTER TABLE OS_ACT ADD CONSTRAINT
	FK_ID_OS FOREIGN KEY (ID_OS) REFERENCES OS (ID);

ALTER TABLE OS_ACT ADD CONSTRAINT
	FK_ID_ACT FOREIGN KEY (ID_ACT) REFERENCES ACT (ID);

--DELETE FROM OS_ACT;
--DELETE FROM OS;
--DELETE FROM ACT;
--DROP TABLE OS_ACT;
--DROP TABLE OS;
--DROP TABLE ACT;
