using System;
using System.Collections.Generic;

namespace GenScenarios.Models
{
    public partial class OsAct
    {
        public int IdOs { get; set; }
        public int IdAct { get; set; }

        public OsAct(int idos, int idact)
        {
            IdOs = idos;
            IdAct = idact;
        }

        public static List<OsAct> OsActTable()
        {
            return new List<OsAct>()
            {
                //OS 1-5 ACT 1-29 31
                new OsAct (1, 1 ),
                new OsAct (1, 2 ),
                new OsAct (1, 3 ),
                new OsAct (1, 4 ),
                new OsAct (1, 5 ),
                new OsAct (1, 6 ),
                new OsAct (1, 7 ),
                new OsAct (1, 8 ),
                new OsAct (1, 9 ),
                new OsAct (1, 10),
                new OsAct (1, 11),
                new OsAct (1, 12),
                new OsAct (1, 13),
                new OsAct (1, 14),
                new OsAct (1, 15),
                new OsAct (1, 16),
                new OsAct (1, 17),
                new OsAct (1, 18),
                new OsAct (1, 19),
                new OsAct (1, 20),
                new OsAct (1, 21),
                new OsAct (1, 22),
                new OsAct (1, 23),
                new OsAct (1, 24),
                new OsAct (1, 25),
                new OsAct (1, 26),
                new OsAct (1, 27),
                new OsAct (1, 28),
                new OsAct (1, 29),
                new OsAct (1, 31),

                new OsAct (2, 1 ),
                new OsAct (2, 2 ),
                new OsAct (2, 3 ),
                new OsAct (2, 4 ),
                new OsAct (2, 5 ),
                new OsAct (2, 6 ),
                new OsAct (2, 7 ),
                new OsAct (2, 8 ),
                new OsAct (2, 9 ),
                new OsAct (2, 10),
                new OsAct (2, 11),
                new OsAct (2, 12),
                new OsAct (2, 13),
                new OsAct (2, 14),
                new OsAct (2, 15),
                new OsAct (2, 16),
                new OsAct (2, 17),
                new OsAct (2, 18),
                new OsAct (2, 19),
                new OsAct (2, 20),
                new OsAct (2, 21),
                new OsAct (2, 22),
                new OsAct (2, 23),
                new OsAct (2, 24),
                new OsAct (2, 25),
                new OsAct (2, 26),
                new OsAct (2, 27),
                new OsAct (2, 28),
                new OsAct (2, 29),
                new OsAct (2, 31),

                new OsAct (3, 1 ),
                new OsAct (3, 2 ),
                new OsAct (3, 3 ),
                new OsAct (3, 4 ),
                new OsAct (3, 5 ),
                new OsAct (3, 6 ),
                new OsAct (3, 7 ),
                new OsAct (3, 8 ),
                new OsAct (3, 9 ),
                new OsAct (3, 10),
                new OsAct (3, 11),
                new OsAct (3, 12),
                new OsAct (3, 13),
                new OsAct (3, 14),
                new OsAct (3, 15),
                new OsAct (3, 16),
                new OsAct (3, 17),
                new OsAct (3, 18),
                new OsAct (3, 19),
                new OsAct (3, 20),
                new OsAct (3, 21),
                new OsAct (3, 22),
                new OsAct (3, 23),
                new OsAct (3, 24),
                new OsAct (3, 25),
                new OsAct (3, 26),
                new OsAct (3, 27),
                new OsAct (3, 28),
                new OsAct (3, 29),
                new OsAct (3, 31),

                new OsAct (4, 1 ),
                new OsAct (4, 2 ),
                new OsAct (4, 3 ),
                new OsAct (4, 4 ),
                new OsAct (4, 5 ),
                new OsAct (4, 6 ),
                new OsAct (4, 7 ),
                new OsAct (4, 8 ),
                new OsAct (4, 9 ),
                new OsAct (4, 10),
                new OsAct (4, 11),
                new OsAct (4, 12),
                new OsAct (4, 13),
                new OsAct (4, 14),
                new OsAct (4, 15),
                new OsAct (4, 16),
                new OsAct (4, 17),
                new OsAct (4, 18),
                new OsAct (4, 19),
                new OsAct (4, 20),
                new OsAct (4, 21),
                new OsAct (4, 22),
                new OsAct (4, 23),
                new OsAct (4, 24),
                new OsAct (4, 25),
                new OsAct (4, 26),
                new OsAct (4, 27),
                new OsAct (4, 28),
                new OsAct (4, 29),
                new OsAct (4, 31),

                new OsAct (5, 1 ),
                new OsAct (5, 2 ),
                new OsAct (5, 3 ),
                new OsAct (5, 4 ),
                new OsAct (5, 5 ),
                new OsAct (5, 6 ),
                new OsAct (5, 7 ),
                new OsAct (5, 8 ),
                new OsAct (5, 9 ),
                new OsAct (5, 10),
                new OsAct (5, 11),
                new OsAct (5, 12),
                new OsAct (5, 13),
                new OsAct (5, 14),
                new OsAct (5, 15),
                new OsAct (5, 16),
                new OsAct (5, 17),
                new OsAct (5, 18),
                new OsAct (5, 19),
                new OsAct (5, 20),
                new OsAct (5, 21),
                new OsAct (5, 22),
                new OsAct (5, 23),
                new OsAct (5, 24),
                new OsAct (5, 25),
                new OsAct (5, 26),
                new OsAct (5, 27),
                new OsAct (5, 28),
                new OsAct (5, 29),
                new OsAct (5, 31),

//OS 6-9 ACT 1-3 14 30-32 37//////////////////////////////////////////////////////////////////////////////-
                new OsAct (6, 1 ),
                new OsAct (6, 2 ),
                new OsAct (6, 3 ),
                new OsAct (6, 14),
                new OsAct (6, 30),
                new OsAct (6, 31),
                new OsAct (6, 32),

                new OsAct (7, 1 ),
                new OsAct (7, 2 ),
                new OsAct (7, 3 ),
                new OsAct (7, 14),
                new OsAct (7, 30),
                new OsAct (7, 31),
                new OsAct (7, 32),

                new OsAct (8, 1 ),
                new OsAct (8, 2 ),
                new OsAct (8, 3 ),
                new OsAct (8, 14),
                new OsAct (8, 30),
                new OsAct (8, 31),
                new OsAct (8, 32),

                new OsAct (9, 1 ),
                new OsAct (9, 2 ),
                new OsAct (9, 3 ),
                new OsAct (9, 14),
                new OsAct (9, 30),
                new OsAct (9, 31),
                new OsAct (9, 32),

//OS 10-41 ACT 1 5 9 12 13 18-29 33-36////////////////////////////////////////////////////////////////////////-
                new OsAct (10, 1 ),
                new OsAct (10, 5 ),
                new OsAct (10, 9 ),
                new OsAct (10, 12),
                new OsAct (10, 13),
                new OsAct (10, 18),
                new OsAct (10, 19),
                new OsAct (10, 20),
                new OsAct (10, 21),
                new OsAct (10, 22),
                new OsAct (10, 23),
                new OsAct (10, 24),
                new OsAct (10, 25),
                new OsAct (10, 26),
                new OsAct (10, 27),
                new OsAct (10, 28),
                new OsAct (10, 29),
                new OsAct (10, 33),
                new OsAct (10, 34),
                new OsAct (10, 35),
                new OsAct (10, 36),

                new OsAct (11, 1 ),
                new OsAct (11, 5 ),
                new OsAct (11, 9 ),
                new OsAct (11, 12),
                new OsAct (11, 13),
                new OsAct (11, 18),
                new OsAct (11, 19),
                new OsAct (11, 20),
                new OsAct (11, 21),
                new OsAct (11, 22),
                new OsAct (11, 23),
                new OsAct (11, 24),
                new OsAct (11, 25),
                new OsAct (11, 26),
                new OsAct (11, 27),
                new OsAct (11, 28),
                new OsAct (11, 29),
                new OsAct (11, 33),
                new OsAct (11, 34),
                new OsAct (11, 35),
                new OsAct (11, 36),

                new OsAct (12, 1 ),
                new OsAct (12, 5 ),
                new OsAct (12, 9 ),
                new OsAct (12, 12),
                new OsAct (12, 13),
                new OsAct (12, 18),
                new OsAct (12, 19),
                new OsAct (12, 20),
                new OsAct (12, 21),
                new OsAct (12, 22),
                new OsAct (12, 23),
                new OsAct (12, 24),
                new OsAct (12, 25),
                new OsAct (12, 26),
                new OsAct (12, 27),
                new OsAct (12, 28),
                new OsAct (12, 29),
                new OsAct (12, 33),
                new OsAct (12, 34),
                new OsAct (12, 35),
                new OsAct (12, 36),

                new OsAct (13, 1 ),
                new OsAct (13, 5 ),
                new OsAct (13, 9 ),
                new OsAct (13, 12),
                new OsAct (13, 13),
                new OsAct (13, 18),
                new OsAct (13, 19),
                new OsAct (13, 20),
                new OsAct (13, 21),
                new OsAct (13, 22),
                new OsAct (13, 23),
                new OsAct (13, 24),
                new OsAct (13, 25),
                new OsAct (13, 26),
                new OsAct (13, 27),
                new OsAct (13, 28),
                new OsAct (13, 29),
                new OsAct (13, 33),
                new OsAct (13, 34),
                new OsAct (13, 35),
                new OsAct (13, 36),

                new OsAct (14, 1 ),
                new OsAct (14, 5 ),
                new OsAct (14, 9 ),
                new OsAct (14, 12),
                new OsAct (14, 13),
                new OsAct (14, 18),
                new OsAct (14, 19),
                new OsAct (14, 20),
                new OsAct (14, 21),
                new OsAct (14, 22),
                new OsAct (14, 23),
                new OsAct (14, 24),
                new OsAct (14, 25),
                new OsAct (14, 26),
                new OsAct (14, 27),
                new OsAct (14, 28),
                new OsAct (14, 29),
                new OsAct (14, 33),
                new OsAct (14, 34),
                new OsAct (14, 35),
                new OsAct (14, 36),

                new OsAct (15, 1 ),
                new OsAct (15, 5 ),
                new OsAct (15, 9 ),
                new OsAct (15, 12),
                new OsAct (15, 13),
                new OsAct (15, 18),
                new OsAct (15, 19),
                new OsAct (15, 20),
                new OsAct (15, 21),
                new OsAct (15, 22),
                new OsAct (15, 23),
                new OsAct (15, 24),
                new OsAct (15, 25),
                new OsAct (15, 26),
                new OsAct (15, 27),
                new OsAct (15, 28),
                new OsAct (15, 29),
                new OsAct (15, 33),
                new OsAct (15, 34),
                new OsAct (15, 35),
                new OsAct (15, 36),

                new OsAct (16, 1 ),
                new OsAct (16, 5 ),
                new OsAct (16, 9 ),
                new OsAct (16, 12),
                new OsAct (16, 13),
                new OsAct (16, 18),
                new OsAct (16, 19),
                new OsAct (16, 20),
                new OsAct (16, 21),
                new OsAct (16, 22),
                new OsAct (16, 23),
                new OsAct (16, 24),
                new OsAct (16, 25),
                new OsAct (16, 26),
                new OsAct (16, 27),
                new OsAct (16, 28),
                new OsAct (16, 29),
                new OsAct (16, 33),
                new OsAct (16, 34),
                new OsAct (16, 35),
                new OsAct (16, 36),

                new OsAct (17, 1 ),
                new OsAct (17, 5 ),
                new OsAct (17, 9 ),
                new OsAct (17, 12),
                new OsAct (17, 13),
                new OsAct (17, 18),
                new OsAct (17, 19),
                new OsAct (17, 20),
                new OsAct (17, 21),
                new OsAct (17, 22),
                new OsAct (17, 23),
                new OsAct (17, 24),
                new OsAct (17, 25),
                new OsAct (17, 26),
                new OsAct (17, 27),
                new OsAct (17, 28),
                new OsAct (17, 29),
                new OsAct (17, 33),
                new OsAct (17, 34),
                new OsAct (17, 35),
                new OsAct (17, 36),

                new OsAct (18, 1 ),
                new OsAct (18, 5 ),
                new OsAct (18, 9 ),
                new OsAct (18, 12),
                new OsAct (18, 13),
                new OsAct (18, 18),
                new OsAct (18, 19),
                new OsAct (18, 20),
                new OsAct (18, 21),
                new OsAct (18, 22),
                new OsAct (18, 23),
                new OsAct (18, 24),
                new OsAct (18, 25),
                new OsAct (18, 26),
                new OsAct (18, 27),
                new OsAct (18, 28),
                new OsAct (18, 29),
                new OsAct (18, 33),
                new OsAct (18, 34),
                new OsAct (18, 35),
                new OsAct (18, 36),

                new OsAct (19, 1 ),
                new OsAct (19, 5 ),
                new OsAct (19, 9 ),
                new OsAct (19, 12),
                new OsAct (19, 13),
                new OsAct (19, 18),
                new OsAct (19, 19),
                new OsAct (19, 20),
                new OsAct (19, 21),
                new OsAct (19, 22),
                new OsAct (19, 23),
                new OsAct (19, 24),
                new OsAct (19, 25),
                new OsAct (19, 26),
                new OsAct (19, 27),
                new OsAct (19, 28),
                new OsAct (19, 29),
                new OsAct (19, 33),
                new OsAct (19, 34),
                new OsAct (19, 35),
                new OsAct (19, 36),

                new OsAct (20, 1 ),
                new OsAct (20, 5 ),
                new OsAct (20, 9 ),
                new OsAct (20, 12),
                new OsAct (20, 13),
                new OsAct (20, 18),
                new OsAct (20, 19),
                new OsAct (20, 20),
                new OsAct (20, 21),
                new OsAct (20, 22),
                new OsAct (20, 23),
                new OsAct (20, 24),
                new OsAct (20, 25),
                new OsAct (20, 26),
                new OsAct (20, 27),
                new OsAct (20, 28),
                new OsAct (20, 29),
                new OsAct (20, 33),
                new OsAct (20, 34),
                new OsAct (20, 35),
                new OsAct (20, 36),

                new OsAct (21, 1 ),
                new OsAct (21, 5 ),
                new OsAct (21, 9 ),
                new OsAct (21, 12),
                new OsAct (21, 13),
                new OsAct (21, 18),
                new OsAct (21, 19),
                new OsAct (21, 20),
                new OsAct (21, 21),
                new OsAct (21, 22),
                new OsAct (21, 23),
                new OsAct (21, 24),
                new OsAct (21, 25),
                new OsAct (21, 26),
                new OsAct (21, 27),
                new OsAct (21, 28),
                new OsAct (21, 29),
                new OsAct (21, 33),
                new OsAct (21, 34),
                new OsAct (21, 35),
                new OsAct (21, 36),

                new OsAct (22, 1 ),
                new OsAct (22, 5 ),
                new OsAct (22, 9 ),
                new OsAct (22, 12),
                new OsAct (22, 13),
                new OsAct (22, 18),
                new OsAct (22, 19),
                new OsAct (22, 20),
                new OsAct (22, 21),
                new OsAct (22, 22),
                new OsAct (22, 23),
                new OsAct (22, 24),
                new OsAct (22, 25),
                new OsAct (22, 26),
                new OsAct (22, 27),
                new OsAct (22, 28),
                new OsAct (22, 29),
                new OsAct (22, 33),
                new OsAct (22, 34),
                new OsAct (22, 35),
                new OsAct (22, 36),

                new OsAct (23, 1 ),
                new OsAct (23, 5 ),
                new OsAct (23, 9 ),
                new OsAct (23, 12),
                new OsAct (23, 13),
                new OsAct (23, 18),
                new OsAct (23, 19),
                new OsAct (23, 20),
                new OsAct (23, 21),
                new OsAct (23, 22),
                new OsAct (23, 23),
                new OsAct (23, 24),
                new OsAct (23, 25),
                new OsAct (23, 26),
                new OsAct (23, 27),
                new OsAct (23, 28),
                new OsAct (23, 29),
                new OsAct (23, 33),
                new OsAct (23, 34),
                new OsAct (23, 35),
                new OsAct (23, 36),

                new OsAct (24, 1 ),
                new OsAct (24, 5 ),
                new OsAct (24, 9 ),
                new OsAct (24, 12),
                new OsAct (24, 13),
                new OsAct (24, 18),
                new OsAct (24, 19),
                new OsAct (24, 20),
                new OsAct (24, 21),
                new OsAct (24, 22),
                new OsAct (24, 23),
                new OsAct (24, 24),
                new OsAct (24, 25),
                new OsAct (24, 26),
                new OsAct (24, 27),
                new OsAct (24, 28),
                new OsAct (24, 29),
                new OsAct (24, 33),
                new OsAct (24, 34),
                new OsAct (24, 35),
                new OsAct (24, 36),

                new OsAct (25, 1 ),
                new OsAct (25, 5 ),
                new OsAct (25, 9 ),
                new OsAct (25, 12),
                new OsAct (25, 13),
                new OsAct (25, 18),
                new OsAct (25, 19),
                new OsAct (25, 20),
                new OsAct (25, 21),
                new OsAct (25, 22),
                new OsAct (25, 23),
                new OsAct (25, 24),
                new OsAct (25, 25),
                new OsAct (25, 26),
                new OsAct (25, 27),
                new OsAct (25, 28),
                new OsAct (25, 29),
                new OsAct (25, 33),
                new OsAct (25, 34),
                new OsAct (25, 35),
                new OsAct (25, 36),

                new OsAct (26, 1 ),
                new OsAct (26, 5 ),
                new OsAct (26, 9 ),
                new OsAct (26, 12),
                new OsAct (26, 13),
                new OsAct (26, 18),
                new OsAct (26, 19),
                new OsAct (26, 20),
                new OsAct (26, 21),
                new OsAct (26, 22),
                new OsAct (26, 23),
                new OsAct (26, 24),
                new OsAct (26, 25),
                new OsAct (26, 26),
                new OsAct (26, 27),
                new OsAct (26, 28),
                new OsAct (26, 29),
                new OsAct (26, 33),
                new OsAct (26, 34),
                new OsAct (26, 35),
                new OsAct (26, 36),

                new OsAct (27, 1 ),
                new OsAct (27, 5 ),
                new OsAct (27, 9 ),
                new OsAct (27, 12),
                new OsAct (27, 13),
                new OsAct (27, 18),
                new OsAct (27, 19),
                new OsAct (27, 20),
                new OsAct (27, 21),
                new OsAct (27, 22),
                new OsAct (27, 23),
                new OsAct (27, 24),
                new OsAct (27, 25),
                new OsAct (27, 26),
                new OsAct (27, 27),
                new OsAct (27, 28),
                new OsAct (27, 29),
                new OsAct (27, 33),
                new OsAct (27, 34),
                new OsAct (27, 35),
                new OsAct (27, 36),

                new OsAct (28, 1 ),
                new OsAct (28, 5 ),
                new OsAct (28, 9 ),
                new OsAct (28, 12),
                new OsAct (28, 13),
                new OsAct (28, 18),
                new OsAct (28, 19),
                new OsAct (28, 20),
                new OsAct (28, 21),
                new OsAct (28, 22),
                new OsAct (28, 23),
                new OsAct (28, 24),
                new OsAct (28, 25),
                new OsAct (28, 26),
                new OsAct (28, 27),
                new OsAct (28, 28),
                new OsAct (28, 29),
                new OsAct (28, 33),
                new OsAct (28, 34),
                new OsAct (28, 35),
                new OsAct (28, 36),

                new OsAct (29, 1 ),
                new OsAct (29, 5 ),
                new OsAct (29, 9 ),
                new OsAct (29, 12),
                new OsAct (29, 13),
                new OsAct (29, 18),
                new OsAct (29, 19),
                new OsAct (29, 20),
                new OsAct (29, 21),
                new OsAct (29, 22),
                new OsAct (29, 23),
                new OsAct (29, 24),
                new OsAct (29, 25),
                new OsAct (29, 26),
                new OsAct (29, 27),
                new OsAct (29, 28),
                new OsAct (29, 29),
                new OsAct (29, 33),
                new OsAct (29, 34),
                new OsAct (29, 35),
                new OsAct (29, 36),

                new OsAct (30, 1 ),
                new OsAct (30, 5 ),
                new OsAct (30, 9 ),
                new OsAct (30, 12),
                new OsAct (30, 13),
                new OsAct (30, 18),
                new OsAct (30, 19),
                new OsAct (30, 20),
                new OsAct (30, 21),
                new OsAct (30, 22),
                new OsAct (30, 23),
                new OsAct (30, 24),
                new OsAct (30, 25),
                new OsAct (30, 26),
                new OsAct (30, 27),
                new OsAct (30, 28),
                new OsAct (30, 29),
                new OsAct (30, 33),
                new OsAct (30, 34),
                new OsAct (30, 35),
                new OsAct (30, 36),

                new OsAct (31, 1 ),
                new OsAct (31, 5 ),
                new OsAct (31, 9 ),
                new OsAct (31, 12),
                new OsAct (31, 13),
                new OsAct (31, 18),
                new OsAct (31, 19),
                new OsAct (31, 20),
                new OsAct (31, 21),
                new OsAct (31, 22),
                new OsAct (31, 23),
                new OsAct (31, 24),
                new OsAct (31, 25),
                new OsAct (31, 26),
                new OsAct (31, 27),
                new OsAct (31, 28),
                new OsAct (31, 29),
                new OsAct (31, 33),
                new OsAct (31, 34),
                new OsAct (31, 35),
                new OsAct (31, 36),

                new OsAct (32, 1 ),
                new OsAct (32, 5 ),
                new OsAct (32, 9 ),
                new OsAct (32, 12),
                new OsAct (32, 13),
                new OsAct (32, 18),
                new OsAct (32, 19),
                new OsAct (32, 20),
                new OsAct (32, 21),
                new OsAct (32, 22),
                new OsAct (32, 23),
                new OsAct (32, 24),
                new OsAct (32, 25),
                new OsAct (32, 26),
                new OsAct (32, 27),
                new OsAct (32, 28),
                new OsAct (32, 29),
                new OsAct (32, 33),
                new OsAct (32, 34),
                new OsAct (32, 35),
                new OsAct (32, 36),

                new OsAct (33, 1 ),
                new OsAct (33, 5 ),
                new OsAct (33, 9 ),
                new OsAct (33, 12),
                new OsAct (33, 13),
                new OsAct (33, 18),
                new OsAct (33, 19),
                new OsAct (33, 20),
                new OsAct (33, 21),
                new OsAct (33, 22),
                new OsAct (33, 23),
                new OsAct (33, 24),
                new OsAct (33, 25),
                new OsAct (33, 26),
                new OsAct (33, 27),
                new OsAct (33, 28),
                new OsAct (33, 29),
                new OsAct (33, 33),
                new OsAct (33, 34),
                new OsAct (33, 35),
                new OsAct (33, 36),

                new OsAct (34, 1 ),
                new OsAct (34, 5 ),
                new OsAct (34, 9 ),
                new OsAct (34, 12),
                new OsAct (34, 13),
                new OsAct (34, 18),
                new OsAct (34, 19),
                new OsAct (34, 20),
                new OsAct (34, 21),
                new OsAct (34, 22),
                new OsAct (34, 23),
                new OsAct (34, 24),
                new OsAct (34, 25),
                new OsAct (34, 26),
                new OsAct (34, 27),
                new OsAct (34, 28),
                new OsAct (34, 29),
                new OsAct (34, 33),
                new OsAct (34, 34),
                new OsAct (34, 35),
                new OsAct (34, 36),

                new OsAct (35, 1 ),
                new OsAct (35, 5 ),
                new OsAct (35, 9 ),
                new OsAct (35, 12),
                new OsAct (35, 13),
                new OsAct (35, 18),
                new OsAct (35, 19),
                new OsAct (35, 20),
                new OsAct (35, 21),
                new OsAct (35, 22),
                new OsAct (35, 23),
                new OsAct (35, 24),
                new OsAct (35, 25),
                new OsAct (35, 26),
                new OsAct (35, 27),
                new OsAct (35, 28),
                new OsAct (35, 29),
                new OsAct (35, 33),
                new OsAct (35, 34),
                new OsAct (35, 35),
                new OsAct (35, 36),

                new OsAct (36, 1 ),
                new OsAct (36, 5 ),
                new OsAct (36, 9 ),
                new OsAct (36, 12),
                new OsAct (36, 13),
                new OsAct (36, 18),
                new OsAct (36, 19),
                new OsAct (36, 20),
                new OsAct (36, 21),
                new OsAct (36, 22),
                new OsAct (36, 23),
                new OsAct (36, 24),
                new OsAct (36, 25),
                new OsAct (36, 26),
                new OsAct (36, 27),
                new OsAct (36, 28),
                new OsAct (36, 29),
                new OsAct (36, 33),
                new OsAct (36, 34),
                new OsAct (36, 35),
                new OsAct (36, 36),

                new OsAct (37, 1 ),
                new OsAct (37, 5 ),
                new OsAct (37, 9 ),
                new OsAct (37, 12),
                new OsAct (37, 13),
                new OsAct (37, 18),
                new OsAct (37, 19),
                new OsAct (37, 20),
                new OsAct (37, 21),
                new OsAct (37, 22),
                new OsAct (37, 23),
                new OsAct (37, 24),
                new OsAct (37, 25),
                new OsAct (37, 26),
                new OsAct (37, 27),
                new OsAct (37, 28),
                new OsAct (37, 29),
                new OsAct (37, 33),
                new OsAct (37, 34),
                new OsAct (37, 35),
                new OsAct (37, 36),

                new OsAct (38, 1 ),
                new OsAct (38, 5 ),
                new OsAct (38, 9 ),
                new OsAct (38, 12),
                new OsAct (38, 13),
                new OsAct (38, 18),
                new OsAct (38, 19),
                new OsAct (38, 20),
                new OsAct (38, 21),
                new OsAct (38, 22),
                new OsAct (38, 23),
                new OsAct (38, 24),
                new OsAct (38, 25),
                new OsAct (38, 26),
                new OsAct (38, 27),
                new OsAct (38, 28),
                new OsAct (38, 29),
                new OsAct (38, 33),
                new OsAct (38, 34),
                new OsAct (38, 35),
                new OsAct (38, 36),

                new OsAct (39, 1 ),
                new OsAct (39, 5 ),
                new OsAct (39, 9 ),
                new OsAct (39, 12),
                new OsAct (39, 13),
                new OsAct (39, 18),
                new OsAct (39, 19),
                new OsAct (39, 20),
                new OsAct (39, 21),
                new OsAct (39, 22),
                new OsAct (39, 23),
                new OsAct (39, 24),
                new OsAct (39, 25),
                new OsAct (39, 26),
                new OsAct (39, 27),
                new OsAct (39, 28),
                new OsAct (39, 29),
                new OsAct (39, 33),
                new OsAct (39, 34),
                new OsAct (39, 35),
                new OsAct (39, 36),

                new OsAct (40, 1 ),
                new OsAct (40, 5 ),
                new OsAct (40, 9 ),
                new OsAct (40, 12),
                new OsAct (40, 13),
                new OsAct (40, 18),
                new OsAct (40, 19),
                new OsAct (40, 20),
                new OsAct (40, 21),
                new OsAct (40, 22),
                new OsAct (40, 23),
                new OsAct (40, 24),
                new OsAct (40, 25),
                new OsAct (40, 26),
                new OsAct (40, 27),
                new OsAct (40, 28),
                new OsAct (40, 29),
                new OsAct (40, 33),
                new OsAct (40, 34),
                new OsAct (40, 35),
                new OsAct (40, 36),

                new OsAct (41, 1 ),
                new OsAct (41, 5 ),
                new OsAct (41, 9 ),
                new OsAct (41, 12),
                new OsAct (41, 13),
                new OsAct (41, 18),
                new OsAct (41, 19),
                new OsAct (41, 20),
                new OsAct (41, 21),
                new OsAct (41, 22),
                new OsAct (41, 23),
                new OsAct (41, 24),
                new OsAct (41, 25),
                new OsAct (41, 26),
                new OsAct (41, 27),
                new OsAct (41, 28),
                new OsAct (41, 29),
                new OsAct (41, 33),
                new OsAct (41, 34),
                new OsAct (41, 35),
                new OsAct (41, 36),

//OS 42-55 ACT 1 2 12 13 18-29
                new OsAct (42, 1 ),
                new OsAct (42, 2 ),
                new OsAct (42, 12),
                new OsAct (42, 13),
                new OsAct (42, 18),
                new OsAct (42, 19),
                new OsAct (42, 20),
                new OsAct (42, 21),
                new OsAct (42, 22),
                new OsAct (42, 23),
                new OsAct (42, 24),
                new OsAct (42, 25),
                new OsAct (42, 26),
                new OsAct (42, 27),
                new OsAct (42, 28),
                new OsAct (42, 29),

                new OsAct (43, 1 ),
                new OsAct (43, 2 ),
                new OsAct (43, 12),
                new OsAct (43, 13),
                new OsAct (43, 18),
                new OsAct (43, 19),
                new OsAct (43, 20),
                new OsAct (43, 21),
                new OsAct (43, 22),
                new OsAct (43, 23),
                new OsAct (43, 24),
                new OsAct (43, 25),
                new OsAct (43, 26),
                new OsAct (43, 27),
                new OsAct (43, 28),
                new OsAct (43, 29),

                new OsAct (44, 1 ),
                new OsAct (44, 2 ),
                new OsAct (44, 12),
                new OsAct (44, 13),
                new OsAct (44, 18),
                new OsAct (44, 19),
                new OsAct (44, 20),
                new OsAct (44, 21),
                new OsAct (44, 22),
                new OsAct (44, 23),
                new OsAct (44, 24),
                new OsAct (44, 25),
                new OsAct (44, 26),
                new OsAct (44, 27),
                new OsAct (44, 28),
                new OsAct (44, 29),

                new OsAct (45, 1 ),
                new OsAct (45, 2 ),
                new OsAct (45, 12),
                new OsAct (45, 13),
                new OsAct (45, 18),
                new OsAct (45, 19),
                new OsAct (45, 20),
                new OsAct (45, 21),
                new OsAct (45, 22),
                new OsAct (45, 23),
                new OsAct (45, 24),
                new OsAct (45, 25),
                new OsAct (45, 26),
                new OsAct (45, 27),
                new OsAct (45, 28),
                new OsAct (45, 29),

                new OsAct (46, 1 ),
                new OsAct (46, 2 ),
                new OsAct (46, 12),
                new OsAct (46, 13),
                new OsAct (46, 18),
                new OsAct (46, 19),
                new OsAct (46, 20),
                new OsAct (46, 21),
                new OsAct (46, 22),
                new OsAct (46, 23),
                new OsAct (46, 24),
                new OsAct (46, 25),
                new OsAct (46, 26),
                new OsAct (46, 27),
                new OsAct (46, 28),
                new OsAct (46, 29),

                new OsAct (47, 1 ),
                new OsAct (47, 2 ),
                new OsAct (47, 12),
                new OsAct (47, 13),
                new OsAct (47, 18),
                new OsAct (47, 19),
                new OsAct (47, 20),
                new OsAct (47, 21),
                new OsAct (47, 22),
                new OsAct (47, 23),
                new OsAct (47, 24),
                new OsAct (47, 25),
                new OsAct (47, 26),
                new OsAct (47, 27),
                new OsAct (47, 28),
                new OsAct (47, 29),

                new OsAct (48, 1 ),
                new OsAct (48, 2 ),
                new OsAct (48, 12),
                new OsAct (48, 13),
                new OsAct (48, 18),
                new OsAct (48, 19),
                new OsAct (48, 20),
                new OsAct (48, 21),
                new OsAct (48, 22),
                new OsAct (48, 23),
                new OsAct (48, 24),
                new OsAct (48, 25),
                new OsAct (48, 26),
                new OsAct (48, 27),
                new OsAct (48, 28),
                new OsAct (48, 29),

                new OsAct (49, 1 ),
                new OsAct (49, 2 ),
                new OsAct (49, 12),
                new OsAct (49, 13),
                new OsAct (49, 18),
                new OsAct (49, 19),
                new OsAct (49, 20),
                new OsAct (49, 21),
                new OsAct (49, 22),
                new OsAct (49, 23),
                new OsAct (49, 24),
                new OsAct (49, 25),
                new OsAct (49, 26),
                new OsAct (49, 27),
                new OsAct (49, 28),
                new OsAct (49, 29),

                new OsAct (50, 1 ),
                new OsAct (50, 2 ),
                new OsAct (50, 12),
                new OsAct (50, 13),
                new OsAct (50, 18),
                new OsAct (50, 19),
                new OsAct (50, 20),
                new OsAct (50, 21),
                new OsAct (50, 22),
                new OsAct (50, 23),
                new OsAct (50, 24),
                new OsAct (50, 25),
                new OsAct (50, 26),
                new OsAct (50, 27),
                new OsAct (50, 28),
                new OsAct (50, 29),

                new OsAct (51, 1 ),
                new OsAct (51, 2 ),
                new OsAct (51, 12),
                new OsAct (51, 13),
                new OsAct (51, 18),
                new OsAct (51, 19),
                new OsAct (51, 20),
                new OsAct (51, 21),
                new OsAct (51, 22),
                new OsAct (51, 23),
                new OsAct (51, 24),
                new OsAct (51, 25),
                new OsAct (51, 26),
                new OsAct (51, 27),
                new OsAct (51, 28),
                new OsAct (51, 29),

                new OsAct (52, 1 ),
                new OsAct (52, 2 ),
                new OsAct (52, 12),
                new OsAct (52, 13),
                new OsAct (52, 18),
                new OsAct (52, 19),
                new OsAct (52, 20),
                new OsAct (52, 21),
                new OsAct (52, 22),
                new OsAct (52, 23),
                new OsAct (52, 24),
                new OsAct (52, 25),
                new OsAct (52, 26),
                new OsAct (52, 27),
                new OsAct (52, 28),
                new OsAct (52, 29),

                new OsAct (53, 1 ),
                new OsAct (53, 2 ),
                new OsAct (53, 12),
                new OsAct (53, 13),
                new OsAct (53, 18),
                new OsAct (53, 19),
                new OsAct (53, 20),
                new OsAct (53, 21),
                new OsAct (53, 22),
                new OsAct (53, 23),
                new OsAct (53, 24),
                new OsAct (53, 25),
                new OsAct (53, 26),
                new OsAct (53, 27),
                new OsAct (53, 28),
                new OsAct (53, 29),

                new OsAct (54, 1 ),
                new OsAct (54, 2 ),
                new OsAct (54, 12),
                new OsAct (54, 13),
                new OsAct (54, 18),
                new OsAct (54, 19),
                new OsAct (54, 20),
                new OsAct (54, 21),
                new OsAct (54, 22),
                new OsAct (54, 23),
                new OsAct (54, 24),
                new OsAct (54, 25),
                new OsAct (54, 26),
                new OsAct (54, 27),
                new OsAct (54, 28),
                new OsAct (54, 29),

                new OsAct (55, 1 ),
                new OsAct (55, 2 ),
                new OsAct (55, 12),
                new OsAct (55, 13),
                new OsAct (55, 18),
                new OsAct (55, 19),
                new OsAct (55, 20),
                new OsAct (55, 21),
                new OsAct (55, 22),
                new OsAct (55, 23),
                new OsAct (55, 24),
                new OsAct (55, 25),
                new OsAct (55, 26),
                new OsAct (55, 27),
                new OsAct (55, 28),
                new OsAct (55, 29)
            };
        }
    }
}
